### PR TITLE
feat(config) Add the `CompilerKind` and `EngineKind` types

### PR DESCRIPTION
**Pull request by Hywan**
This patch introduces the `CompilerKind` and `EngineKind` types.

This patch also introduces the `IsCompilerAvailable` and `IsEngineAvailable` functions. They must be used to check whether a specific compiler or engine is available, otherwise the `Config.Use*Compiler` or `Config.Use*Engine` may panic.

This patch also fixes a bug with the `Config.Use*Compiler` methods where the `wasm_config_set_engine` function was called instead of `wasm_config_set_compiler`.

### CODE REVIEW

**Comment by Hywan** [comment]
bors try

**Review by jubianchi — APPROVED** [review]
Seems good to me, I would just have added a test for `IsCompilerAvailable` but it may only introduce code duplication 🤔

**Comment by Hywan** [comment]
Yeah, it's not that simple to test actually. I consider that if the `TestConfig_AllCombinations` test passes, then it's fine enough for the moment (https://github.com/wasmerio/wasmer-go/blob/9ea145a656745433b56af1ae27bce697a84d0ebe/wasmer/config_test.go#L29).

**Pull request merged**
