### PR TITLE
benchmarks/wagon: use wagon-0.5 and AOT mode

### PR DESCRIPTION
**Pull request by sbinet**
```
  $> benchstat wagon-0.4.txt wagon-0.5-new.txt
  name                          old time/op  new time/op  delta
  _Wagon_Nbody-8                 1.52s ± 1%   1.06s ± 1%  -30.15%  (p=0.000 n=8+10)
  _Wagon_Fibonacci_Recursive-8   2.84s ± 4%   1.71s ± 1%  -39.92%  (p=0.000 n=9+10)
  _Wagon_Pollard_Rho_128-8       1.91s ± 6%   0.94s ± 1%  -50.85%  (p=0.000 n=10+9)
```

### CODE REVIEW

**Comment by sbinet** [comment]
thanks to the awesome work of @twitchyliquid64, `wagon-0.5` is 30-50% faster when AOT mode is enabled. (just thought it would be interesting to bring that up in the `wagon` benchmarks :))

`wasmer` is faster, though :)
```
$> benchstat  wagon-0.5-new.txt wasmer.txt 
name                          old time/op  new time/op  delta
_Nbody-8                 1.05s ± 1%   0.03s ± 1%  -96.69%  (p=0.000 n=9+10)
_Fibonacci_Recursive-8   1.72s ± 1%   0.02s ± 1%  -98.63%  (p=0.000 n=9+9)
_Pollard_Rho_128-8       851ms ± 2%    30ms ± 1%  -96.47%  (p=0.000 n=10+9)
```

**Comment by Hywan** [comment]
Thanks for the PR. It looks interesting!

**Comment by Hywan** [comment]
I don't get the 30-50% you observe. What platform are you using? I'm on macOS.

**Comment by sbinet** [comment]
Yes. For the moment, only Linux amd64 is supported for the AOT mode.

**Comment by Hywan** [comment]
Oh, damn, I've to find a Linux machine just run the benchmarks.

**Comment by sbinet** [comment]
sorry about that :)

**Comment by twitchyliquid64** [comment]
The restriction to Linux is mostly artificial. I need a way to map executable memory, which varies by platform.

I am using the mmap package though, which has support for Darwin & iirc Linux. I _think_ (untested) it should be fine to remove the platform check.

**Comment by twitchyliquid64** [comment]
If you try changing this (https://github.com/go-interpreter/wagon/blob/83c88855b793033e6bb0bb77bf9f3727a5dfeda5/exec/native_compile_nogae.go#L16) to Darwin, i think it will work.

As for why it's only 50% faster (rather than 5x) , I think that's because your benchmarks are comparatively branch-heavy, but wagons native compiler explicitly does not compile branches. I'm also missing support for a good number of instructions (including some basic ones like load memory, Ive been putting off implementing as I need to mitigate spectre).

The fact that cranelift gets wasmer to ~50x faster though shows Ive still got lots of headroom to improve performance. Perhaps I should go ahead and implement that peephole optimiser after all.

**Comment by Hywan** [comment]
I look forward to try the macOS/darwin support :-).

**Comment by syrusakbary** [comment]
Closing the PR as now seems stale. Happy to merge new PRs once the last feedback (macOS/darwin support) is addressed :)

**Pull request closed without merging**
