### PR TITLE
feat(wasmexec) New package: `wasmexec`

### PR DESCRIPTION
**Pull request by Hywan**
This package aims at containing a collection of host functions for
multiple hosts, to support WebAssembly modules compiled by the TinyGo
and the Go compilers.

For the moment, only the Go host is supported, i.e. it's Go host
functions implementations. Host functions have empty implementation.

In the future, it will contain real implementations, and it will be extended
to a Rust, Python, PHP, Ruby implementations.

I wonder though if we should support host functions required by the Go
compiler. It's really focused on JavaScript, plus it is experimental.
cc @MarkMcCaskey @syrusakbary

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
@Hywan I began implementation of this in Wasmer on the Rust side; I almost got Hello World working but we found out there's an existing Rust implementation -- I contacted them about adding a license to their project so that we could possibly use a forked version to avoid duplicating work.  We haven't heard back since posting that issue!

It is a bit messy to support, the ABI is a bit strange for WASM and requires emulating a bit of JS.

**Comment by Hywan** [comment]
Everything is fine.

I think supporting Go Wasm ABI is messy because it's heavily JS centric. However, the TinyGo Wasm ABI is relatively small (2 imports) and make sense outside of a browser.

The question is: Where do we store those implementations? In the wasmer.git repository, nah. In this repository, why not, but it'll contain Python, PHP, Ruby etc. in the future, and I reckon this repository should only contain the `go-ext-wasm` package, not other packages. So, should we create another repository? One that is runtime agnostic.

**Comment by MarkMcCaskey** [comment]
Yeah, I agree -- it's pretty tricky.

In my opinion it depends on if we want to use it in the wasmer CLI binary.  I think, in general, we should keep things related to the Wasmer CLI in the wasmerio/wasmer repo.  If it's just for library use then I don't have an opinion about where it should live (though probably not in wasmerio/wasmer if it's _not_ in the binary)

**Comment by syrusakbary** [comment]
Do we really need this on the go extension? I see it more as a separate addition.

As a note, this project did already the implementation (perhaps people can just use this project)
https://github.com/vedhavyas/go

https://github.com/vedhavyas/go-wasm/blob/master/imports.go

**Comment by Hywan** [comment]
The work done by @vedhavyas looks great! We should also support PHP, Python, Ruby and other implementations, so that Wasm modules emitted by `go` can be used more broadly.

@syrusakbary Should we (Wasmer) lead this effort? If yes, where is the best place to create this project?

**Comment by mjibson** [comment]
I've been trying out this branch and am attempting to pass strings back and forth from Go to the wasm runtime compiled from tinygo. The tinygo file is:

```
//go:export req
func req() int64 {
	s := "blah"
	return int64(uintptr(unsafe.Pointer(&s)))
}
```

And fails during compilation with `not implemented` in `env_resource_write`. I'm new to wasm land. Can you point me in the right direction to implement env_resource_write myself?

**Comment by vedhavyas** [comment]
@Hywan I thought of reaching out to you guys to include the imports as part of the wasmer but decided against it since its very js centric and hoping that would change in the future. Not sure how to proceed for now.

**Comment by Hywan** [comment]
@mjibson That's expected to get a `not implemented` at that progression.
@vedhavyas I think we have a synergy to develop here. I believe it perfectly makes sense to have a Go package to support the Go and TinyGo compilers host functions. I won't find legimitate for Wasmer to “import” your project in the `wasmerio` organisation. However, it makes sense to create a `go-wasm` org, and propose several repositories, like `go`, `javascript`, `python` etc. respectively for the Go implementation, JavaScript implementation, Python implementation etc. for host functions to run Go Wasm modules. Issue is that there is yet no standards to plug host functions to a runtime (we are working on this area though). So including the “go-wasm” project inside Wasmer would imply the code is specific for the Wasmer runtime, and it's not a good idea. Hence the `go-wasm` org. We can help on that area! Thoughts?

**Comment by mjibson** [comment]
Yes, I'm aware. Can you point me in the right direction to implement it?

**Comment by Hywan** [comment]
@mjibson Which compiler did compile your Wasm module: `go` or `tinygo`?

**Comment by vedhavyas** [comment]
@Hywan 

> So including the “go-wasm” project inside Wasmer would imply the code is specific for the Wasmer runtime, and it's not a good idea.
Agree!

>  Issue is that there is yet no standards to plug host functions to a runtime (we are working on this area though)
You mean wasmi. Not sure what you mean by this :-D

It makes sense to create a org `go-wasm` with other language implementations if we have enough excitement from the community to build a port of/ something similar to `go-wasm` in other languages since it is too JS specific? This I'm not sure.

But, IMO, it is safe to give it shot :-D

**Comment by mjibson** [comment]
@Hywan tinygo. I was hoping to implement the solution myself, but I'm new to wasm and so am looking for like a pointer to a doc or something about what I'd need to do. But I'll also try go-wasm.

**Comment by Hywan** [comment]
@vedhavyas 

> You mean wasmi. Not sure what you mean by this :-D

Not wasmi. What is missing right is standard interface to interact with Wasm runtimes. W3C has defined a standard for JS, but standards are missing for C, Go, Python, PHP etc. A draft exist for C (https://github.com/WebAssembly/wasm-c-api), and we are proposing 2 other drafts for Python and PHP (resp. https://github.com/wasmerio/wasm-python-api and https://github.com/wasmerio/wasm-php-api). Nothing yet for Go. Check https://github.com/WebAssembly/design/issues/1290 to learn more.

> It makes sense to create a org go-wasm with other language implementations if we have enough excitement from the community to build a port of/ something similar to go-wasm in other languages since it is too JS specific? This I'm not sure.

What `go-wasm` must provide is a collection of implementations, and then it's up to the Wasm runtime to add a “wrapper”/adapter/bridge to plug this collection into its host function API. I think it's the best strategy. Thoughts?

I see that https://github.com/go-wasm is already reserved :-(. Any name idea?

@mjibson Can you open another issue please? This issue aimed at discussing about defining the implementation, where, and how. I reckon it's a little bit too early to try to solve the intentional “not implemented” issue ;-).

**Comment by vedhavyas** [comment]
> I see that @go-wasm is already reserved :-(. Any name idea?

Maybe `go-wasm-adapter` ?

**Comment by Hywan** [comment]
Yup, let's go with `go-wasm-adapter`. We can change the name later.

**Comment by Hywan** [comment]
@vedhavyas Any progress on that side :-)?

**Comment by vedhavyas** [comment]
@Hywan still on it but with the crisis, I had other things taken care off. I will create the agreed Org and move the go-adapter there.

**Comment by vedhavyas** [comment]
@Hywan the lib is moved here - https://github.com/go-wasm-adapter

**Comment by Hywan** [comment]
<3 thanks!

**Comment by mattn** [comment]
I also implemented Go wasm runtime. https://github.com/mattn/gowasmer

**Comment by Hywan** [comment]
Closing this issue as there is now multiple projects handling this :-).

**Pull request closed without merging**
