### PR TITLE
wasmer-go using WASI program

### PR DESCRIPTION
**Pull request by soulteary**
Supplement the demo of Wasmer-go using WASI program.

### CODE REVIEW

**Comment by soulteary** [comment]
Hi, @Hywan 

In order to let more people quickly get started with wasmer-go, maybe this demo will be helpful.

Thanks to the contributors for making such a useful project.🍻

**Comment by syrusakbary** [comment]
This is great, thanks for the contribution!

**Comment by soulteary** [comment]
Wow, the maintenance team has extremely high efficiency in handling issues, and I hope this project will get better and better.

In addition, I want to know how to contribute documents to this project. The current documents may cause a relatively high threshold for people who are new to the project.

Thanks @syrusakbary

**Comment by syrusakbary** [comment]
@soulteary any contribution on the docs or other part of the project will be always welcomed! Looking forward to it!

**Pull request merged**
