### PR TITLE
feat(function) Implement host function with an environment

### LINKED ISSUE #183: Support Function with an environment
For the moment, we can create new `Function`, but we miss `Function` with a custom user-defined environment.

cc #135

### PR DESCRIPTION
**Pull request by Hywan**
Fix #183.

WIP

Need to double-check everything.

### CODE REVIEW

**Comment by Hywan** [comment]
cc @AdamSLevy you might be interested by this PR :-)

**Comment by jubianchi** [comment]
bors try

**Review by jubianchi — APPROVED** [review]
Seems good to me! LGTM

**Pull request merged**
